---
title: "Hello World Decision Cream"
author: "Siddarta Jairam"
date: "`r strftime(Sys.time(),'%A, %B %d, %Y')`"
output: md_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.width=7.5, fig.height=4,fig.pos='center',echo=TRUE, comment='>',dpi=800)

figList <- list()
tableList <- list()
updateCnt <- function(cnt, nam){
  cnt[[nam]] <- length(cnt) + 1
}
```

This blog is going to have updates on my various projects for R and other platforms. The main project is developing my master's thesis into an actual piece of software. For my other projects that aren't open source or are work related I will post some of my thought processes and ramblings in the form of tutorials and package highlights. Hopefully, this will include extend some of them or making new packages if I see a gap in tools.

The name comes from the fact that "Everyone screams for Decisions". People want the power to make decisions, the right information behind the decision and a complete coverage of the possibilities. They problem is in the delivery. Ice cream delivery has a range of domain specific tools to use including a delivery truck with refrigerating units, cone holders, catchy music blaring over vintage speakers, etc. These tools allow the ice cream truck owner to show everyone that he has a respectable business instead of being a creepy person wanting to talk to children. In the same way, we need the right tools and procedures to sell decisions and everything that makes up that decision.
